# vim: set ts=2 sw=2 tw=0 fo=cnqoj
# Goreleaser configuration
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/b3scalectl
    env:
      - CGO_ENABLED=0
    id: "b3scalectl"
    binary: b3scalectl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "github.com/b3scale/b3scale/pkg/config.Version={{ .Version }}" -X "github.com/b3scale/b3scale/pkg/config.Build={{ .Commit }}"

  - main: ./cmd/b3scalenoded
    env:
      - CGO_ENABLED=0
    id: "b3scalenoded"
    binary: b3scalenoded 
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "github.com/b3scale/b3scale/pkg/config.Version={{ .Version }}" -X "github.com/b3scale/b3scale/pkg/config.Build={{ .Commit }}"

  - main: ./cmd/b3scaleagent
    env:
      - CGO_ENABLED=0
    id: "b3scaleagent"
    binary: b3scaleagent
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "github.com/b3scale/b3scale/pkg/config.Version={{ .Version }}" -X "github.com/b3scale/b3scale/pkg/config.Build={{ .Commit }}"

  - main: ./cmd/b3scaled
    env:
      - CGO_ENABLED=0
    id: "b3scaled"
    binary: b3scaled
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "github.com/b3scale/b3scale/pkg/config.Version={{ .Version }}" -X "github.com/b3scale/b3scale/pkg/config.Build={{ .Commit }}"

archives:
  - id: b3scalectl
    builds: [ b3scalectl ]
    name_template: 'b3scalectl_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

  - id: b3scaled
    builds: [ b3scaled ]
    name_template: 'b3scaled_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

  - id: b3scalenoded
    builds: [ b3scalenoded ]
    name_template: 'b3scalenoded_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

  - id: b3scaleagent
    builds: [ b3scaleagent ]
    name_template: 'b3scaleagent_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

dockers:
  - id: b3scaled
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/b3scale/b3scaled:latest"
      - "ghcr.io/b3scale/b3scaled:{{ .Major }}"
      - "ghcr.io/b3scale/b3scaled:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/b3scale/b3scaled:{{ .Tag }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

nfpms:
  - id: b3scale
    package_name: b3scale
    vendor: "b3scale Authors"
    homepage: https://b3scale.io
    maintainer: Infra.run <mailœinfra.run>
    license: AGPL-3.0-or-later
    description: b3scale daemon
    builds:
      - b3scaled
    formats:
      - deb
    contents:
      - src: examples/b3scale.service
        dst: /lib/systemd/system/b3scale.service
      - src: examples/example.env.b3scaled
        dst: /etc/default/b3scale
        type: "config|noreplace"
        file_info:
          mode: 0600
          owner: bigbluebutton
          group: bigbluebutton
    scripts:
      preinstall: "scripts/preinstall.sh"
      postinstall: "scripts/postinstall.sh"
      postremove: "scripts/postremove.sh"
  - id: b3scaleagent
    package_name: b3scaleagent
    vendor: "b3scale Authors"
    homepage: https://b3scale.io
    maintainer: infra.run <mail@infra.run>
    license: AGPL-3.0-or-later
    description: b3scale information gathering agent for BBB nodes
    builds:
      - b3scaleagent
    formats:
      - deb
    contents:
      - src: examples/b3scaleagent.service
        dst: /lib/systemd/system/b3scaleagent.service
      - src: examples/example.env.b3scaleagent
        dst: /etc/default/b3scaleagent
        type: "config|noreplace"
        file_info:
          mode: 0600
          owner: bigbluebutton
          group: bigbluebutton
    scripts:
      postinstall: "scripts/postinstall.sh"
      postremove: "scripts/postremove.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  disable: true

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" 
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: ./CHANGELOG
