version: '3'

services:
  greenlight:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v2
    container_name: greenlight-v2
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - ./log:/usr/src/app/log
      - ./storage:/usr/src/app/storage

    links:
      - postgres

