
#
# Github Workflow for testing the application
#

name: Test

on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      # Install Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go version

      # Formatting
      - name: Check formatting
        run: |
          test -z $(gofmt -l ./pkg)
          test -z $(gofmt -l ./cmd)

      # Vet
      - name: Vet
        run: |
          go vet ./pkg/...
          go vet ./cmd/...

      # Lint
      - name: Lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status ./pkg/...
          golint -set_exit_status ./cmd/...

      # Test environment
      - name: Setup Test Database
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
        working-directory: ./dev
        run: |
          sudo apt update
          sudo apt install -y postgresql-client
          ./db_create.sh -c -t

      # Run Tests
      - name: Tests
        run: make test
